"""
Coverage collection for stl_mock sources using llvm-cov.

Run with:
    pytest test/test_coverage.py

After the session, the HTML report is written to coverage_html/ and a
text summary is printed. The raw profile data is left in coverage_profiles/
for inspection.

xfail/skip entries are excluded: they abort via sanitizer or CHECK failure
before flushing complete profile data. All other registered tests are
exercised automatically — no manual count to keep up to date.
"""

import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

BINARY = "./stl_test_cov"
PROFDIR = Path("coverage_profiles")
PROFDATA = PROFDIR / "merged.profdata"
REPORT_DIR = Path("coverage_html")
SOURCES = sorted(
    [
        *Path("src").glob("stl_mock*.cpp"),
        *Path("arch/wasm/include").glob("stl_mock*.h"),
    ]
)

# Coverage thresholds — baseline measured 2026-03-08 (src/stl_mock.cpp +
# arch/wasm/include/stl_mock.h). CI fails if any metric drops below these
# values. When coverage genuinely improves, raise the floor here to lock it in.
THRESHOLDS = {
    "region": 90.22,
    "function": 90.91,
    "line": 91.22,
    "branch": 84.00,
}


def _find_llvm_tool(name):
    """Return the llvm tool that matches the clang version in use.

    Matches the compiler version so that profdata generated by clang-N is read
    by llvm-cov-N (version mismatches produce errors). Falls back to the
    unversioned name, then scans recent versions.
    """
    result = subprocess.run(["clang", "--version"], capture_output=True, text=True)
    m = re.search(r"version (\d+)", result.stdout)
    if m:
        versioned = f"{name}-{m.group(1)}"
        if shutil.which(versioned):
            return versioned
    if shutil.which(name):
        return name
    for v in range(25, 13, -1):
        versioned = f"{name}-{v}"
        if shutil.which(versioned):
            return versioned
    raise RuntimeError(f"Could not find {name} or any versioned variant")


LLVM_PROFDATA = _find_llvm_tool("llvm-profdata")
LLVM_COV = _find_llvm_tool("llvm-cov")


def _query(flag):
    return set(
        subprocess.run(
            [BINARY, flag], capture_output=True, text=True, check=True
        ).stdout.splitlines()
    )


def _get_real_tests():
    all_tests = subprocess.run(
        [BINARY, "--list"], capture_output=True, text=True, check=True
    ).stdout.splitlines()
    excluded = _query("--list-xfail") | _query("--list-skip")
    return [n for n in all_tests if n not in excluded]


def _check_thresholds(summary):
    total_line = next(
        (line for line in summary.splitlines() if line.startswith("TOTAL")), None
    )
    if not total_line:
        raise AssertionError("Could not find TOTAL line in coverage report")

    # llvm-cov report columns: Regions, Missed, Region%, Functions, Missed,
    # Function%, Lines, Missed, Line%, Branches, Missed, Branch%
    pcts = [float(x) for x in re.findall(r"(\d+\.\d+)%", total_line)]
    if len(pcts) < 4:
        raise AssertionError(f"Could not parse coverage percentages from: {total_line}")

    measured = dict(zip(("region", "function", "line", "branch"), pcts))
    failures = [
        f"  {metric}: {measured[metric]:.2f}% < threshold {THRESHOLDS[metric]:.2f}%"
        for metric in THRESHOLDS
        if measured[metric] < THRESHOLDS[metric]
    ]
    if failures:
        raise AssertionError("Coverage regression:\n" + "\n".join(failures))


@pytest.fixture(scope="session", autouse=True)
def coverage_report():
    PROFDIR.mkdir(exist_ok=True)
    for f in PROFDIR.glob("*.profraw"):
        f.unlink()

    yield  # tests run here

    profraw = list(PROFDIR.glob("*.profraw"))
    if not profraw:
        print("\nNo profile data collected.")
        return

    subprocess.run(
        [LLVM_PROFDATA, "merge", *profraw, "-o", PROFDATA],
        check=True,
    )

    shutil.rmtree(REPORT_DIR, ignore_errors=True)
    subprocess.run(
        [
            LLVM_COV,
            "show",
            BINARY,
            f"-instr-profile={PROFDATA}",
            "-format=html",
            f"-output-dir={REPORT_DIR}",
            *SOURCES,
        ],
        check=True,
    )

    print(f"\nHTML report: {REPORT_DIR / 'index.html'}\n")
    summary = subprocess.run(
        [LLVM_COV, "report", BINARY, f"-instr-profile={PROFDATA}", *SOURCES],
        capture_output=True,
        text=True,
    ).stdout
    # Write for CI to use in the PR comment; also print for local runs.
    (PROFDIR / "summary.txt").write_text(summary)
    print(summary)

    _check_thresholds(summary)


@pytest.mark.parametrize("name", _get_real_tests())
def test_coverage(name):
    env = {**os.environ, "LLVM_PROFILE_FILE": str(PROFDIR / "%p.profraw")}
    r = subprocess.run(
        [BINARY, "--run", name],
        capture_output=True,
        text=True,
        env=env,
    )
    assert r.returncode == 0, r.stderr + r.stdout
