"""
Coverage collection for stl_mock sources using llvm-cov.

Run with:
    pytest test/test_coverage.py

After the session, the HTML report is written to coverage_html/ and a
text summary is printed. The raw profile data is left in coverage_profiles/
for inspection.

xfail/skip entries are excluded: they abort via sanitizer or CHECK failure
before flushing complete profile data. All other registered tests are
exercised automatically — no manual count to keep up to date.
"""

import glob
import os
import re
import shutil
import subprocess

import pytest

BINARY = "./stl_test_cov"
PROFDIR = "coverage_profiles"
PROFDATA = "coverage_profiles/merged.profdata"
REPORT_DIR = "coverage_html"


def _find_llvm_tool(name):
    """Return the llvm tool that matches the clang version in use.

    Matches the compiler version so that profdata generated by clang-N is read
    by llvm-cov-N (version mismatches produce errors). Falls back to the
    unversioned name, then scans recent versions.
    """
    result = subprocess.run(["clang", "--version"], capture_output=True, text=True)
    m = re.search(r"version (\d+)", result.stdout)
    if m:
        versioned = f"{name}-{m.group(1)}"
        if shutil.which(versioned):
            return versioned
    if shutil.which(name):
        return name
    for v in range(25, 13, -1):
        versioned = f"{name}-{v}"
        if shutil.which(versioned):
            return versioned
    raise RuntimeError(f"Could not find {name} or any versioned variant")


LLVM_PROFDATA = _find_llvm_tool("llvm-profdata")
LLVM_COV = _find_llvm_tool("llvm-cov")

# Glob all stl_mock source files so new files are picked up automatically.
# Test harness files (stl_test_main.cpp, test_framework.h) are excluded
# because they are not part of the code under test.
SOURCES = sorted(glob.glob("src/stl_mock*.cpp"))


def _get_real_tests():
    all_tests = (
        subprocess.run([BINARY, "--list"], capture_output=True, text=True, check=True)
        .stdout.strip()
        .splitlines()
    )
    xfail = set(
        subprocess.run(
            [BINARY, "--list-xfail"], capture_output=True, text=True, check=True
        )
        .stdout.strip()
        .splitlines()
    )
    skip = set(
        subprocess.run(
            [BINARY, "--list-skip"], capture_output=True, text=True, check=True
        )
        .stdout.strip()
        .splitlines()
    )
    return [n for n in all_tests if n not in xfail and n not in skip]


@pytest.fixture(scope="session", autouse=True)
def coverage_report():
    os.makedirs(PROFDIR, exist_ok=True)
    for f in glob.glob(f"{PROFDIR}/*.profraw"):
        os.remove(f)

    yield  # tests run here

    profraw = glob.glob(f"{PROFDIR}/*.profraw")
    if not profraw:
        print("\nNo profile data collected.")
        return

    subprocess.run(
        [LLVM_PROFDATA, "merge", *profraw, "-o", PROFDATA],
        check=True,
    )

    shutil.rmtree(REPORT_DIR, ignore_errors=True)
    subprocess.run(
        [
            LLVM_COV,
            "show",
            BINARY,
            f"-instr-profile={PROFDATA}",
            "-format=html",
            f"-output-dir={REPORT_DIR}",
            *SOURCES,
        ],
        check=True,
    )

    print(f"\nHTML report: {REPORT_DIR}/index.html\n")
    subprocess.run(
        [LLVM_COV, "report", BINARY, f"-instr-profile={PROFDATA}", *SOURCES],
    )


@pytest.mark.parametrize("name", _get_real_tests())
def test_coverage(name):
    env = {**os.environ, "LLVM_PROFILE_FILE": f"{PROFDIR}/%p.profraw"}
    r = subprocess.run(
        [BINARY, "--run", name],
        capture_output=True,
        text=True,
        env=env,
    )
    assert r.returncode == 0, r.stderr + r.stdout
