# .github/workflows/lint.yml
name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      # This runs all hooks against all files.
      # It will fail if any hook makes a change or finds an error.
      run: pre-commit run --all-files --show-diff-on-failure
