# .github/workflows/lint.yml
name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: bash install_requirements.sh
    - name: Add venv to PATH
      run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
    - name: Run prek
      # This runs all hooks against all files.
      # It will fail if any hook makes a change or finds an error.
      run: prek run --all-files --show-diff-on-failure
