name: SCons Build on PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install system dependencies
      run: bash install_requirements.sh

    - name: Add venv to PATH
      run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Run SCons Build
      run: scons

    - name: Run run_single_design tests
      run: pytest test/test_run_single_design.py -v
