name: STL Test (Valgrind)

on:
  pull_request:
    branches:
      - main

jobs:
  stl-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: bash install_requirements.sh

    - name: Add venv to PATH
      run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Install valgrind
      run: sudo apt-get install -y valgrind

    - name: Build stl_test
      run: scons stl_test

    - name: Run stl_test under valgrind
      run: valgrind --error-exitcode=1 --leak-check=full ./stl_test
